default = [
    { type = "ContainerPadding", content = [0, 0, 4] },
    { type = "WorkspacePadding", content = [0, 0, 4] },
]

[keys]
left = { type = "MoveWindow", content = "Left" }
right = { type = "MoveWindow", content = "Right" }
up = { type = "MoveWindow", content = "Up" }
down = { type = "MoveWindow", content = "Down" }

[[window]]
tray = true
[[window.rule]]
type = "exe"
name = "Bitwarden.exe"

[[window]]
bordered = true
tray = true
[[window.rule]]
type = "exe"
name = "Discord.exe"

[[window]]
bordered = true
managed = true
tray = true
[[window.rule]]
type = "exe"
name = "GalaxyClient.exe"

[[window]]
floating = true
[[window.rule]]
type = "class"
name = "Chrome_RenderWidgetHostHWD"

[[window]]
floating = true
[[window.rule]]
type = "exe"
name = "PowerToys.ColorPicker.exe"
[[window.rule]]
type = "exe"
name = "PowerToys.ImageResizer.exe"

[[window]]
bordered = true
floating = true
tray = true
[[window.rule]]
type = "exe"
name = "ProcessHacker.exe"

[[window]]
object_name_change = true
tray = true
[[window.rule]]
type = "exe"
name = "clion64.exe"
[[window.rule]]
type = "exe"
name = "idea64.exe"

[[window]]
floating = true
[[window.rule]]
type = "class"
name = "SunAwtDialog"

[[window]]
bordered = true
tray = true
[[window.rule]]
type = "exe"
name = "lghub.exe"

[[window]]
bordered = true
tray = true
[[window.rule]]
type = "exe"
name = "ShareX.exe"

[[window]]
bordered = true
tray = true
[[window.rule]]
type = "exe"
name = "Spotify.exe"

[[window]]
bordered = true
[[window.rule]]
type = "class"
name = "vguiPopupWindow"

[[window]]
floating = true
[[window.rule]]
type = "class"
name = "TaskManagerWindow"

[[window]]
bordered = true
tray = true
[[window.rule]]
type = "exe"
name = "Telegram.exe"

[[window]]
bordered = true
[[window.rule]]
type = "exe"
name = "Code.exe"

[[window]]
managed = true
[[window.rule]]
type = "class"
name = "ConsoleWindowClass"

[[window]]
floating = true
[[window.rule]]
type = "class"
name = "OperationStatusWindow"
[[window.rule]]
type = "title"
name = "Control Panel"
[[window.rule]]
type = "class"
name = "MsiDialogCloseClass"
